/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppArchiveRouteImport } from './routes/_app/archive'
import { Route as AppDeckRouteImport } from './routes/_app/deck'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTrashRouteImport } from './routes/_app/trash'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppSettingsAdminRouteImport } from './routes/_app/settings/admin'
import { Route as AppSettingsDataRouteImport } from './routes/_app/settings/data'
import { Route as AppSettingsGeneralRouteImport } from './routes/_app/settings/general'
import { Route as AppSettingsUpdateRouteImport } from './routes/_app/settings/update'
import { Route as AppSettingsAdminBackupsRouteImport } from './routes/_app/settings/admin/backups'
import { Route as AppSettingsAdminUsersRouteImport } from './routes/_app/settings/admin/users'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppRoute,
} as any)
const AppDeckRoute = AppDeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAdminRoute = AppSettingsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDataRoute = AppSettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsUpdateRoute = AppSettingsUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAdminBackupsRoute = AppSettingsAdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppSettingsAdminRoute,
} as any)
const AppSettingsAdminUsersRoute = AppSettingsAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/archive': typeof AppArchiveRoute
  '/deck': typeof AppDeckRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/trash': typeof AppTrashRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/admin': typeof AppSettingsAdminRouteWithChildren
  '/settings/data': typeof AppSettingsDataRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/update': typeof AppSettingsUpdateRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/settings/admin/backups': typeof AppSettingsAdminBackupsRoute
  '/settings/admin/users': typeof AppSettingsAdminUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/archive': typeof AppArchiveRoute
  '/deck': typeof AppDeckRoute
  '/search': typeof AppSearchRoute
  '/trash': typeof AppTrashRoute
  '/': typeof AppIndexRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/admin': typeof AppSettingsAdminRouteWithChildren
  '/settings/data': typeof AppSettingsDataRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/update': typeof AppSettingsUpdateRoute
  '/settings': typeof AppSettingsIndexRoute
  '/settings/admin/backups': typeof AppSettingsAdminBackupsRoute
  '/settings/admin/users': typeof AppSettingsAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/archive': typeof AppArchiveRoute
  '/_app/deck': typeof AppDeckRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/trash': typeof AppTrashRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/admin': typeof AppSettingsAdminRouteWithChildren
  '/_app/settings/data': typeof AppSettingsDataRoute
  '/_app/settings/general': typeof AppSettingsGeneralRoute
  '/_app/settings/update': typeof AppSettingsUpdateRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/settings/admin/backups': typeof AppSettingsAdminBackupsRoute
  '/_app/settings/admin/users': typeof AppSettingsAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/archive'
    | '/deck'
    | '/search'
    | '/settings'
    | '/trash'
    | '/settings/account'
    | '/settings/admin'
    | '/settings/data'
    | '/settings/general'
    | '/settings/update'
    | '/settings/'
    | '/settings/admin/backups'
    | '/settings/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/archive'
    | '/deck'
    | '/search'
    | '/trash'
    | '/'
    | '/settings/account'
    | '/settings/admin'
    | '/settings/data'
    | '/settings/general'
    | '/settings/update'
    | '/settings'
    | '/settings/admin/backups'
    | '/settings/admin/users'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/archive'
    | '/_app/deck'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/trash'
    | '/_app/'
    | '/_app/settings/account'
    | '/_app/settings/admin'
    | '/_app/settings/data'
    | '/_app/settings/general'
    | '/_app/settings/update'
    | '/_app/settings/'
    | '/_app/settings/admin/backups'
    | '/_app/settings/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archive': {
      id: '/_app/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AppArchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deck': {
      id: '/_app/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof AppDeckRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/admin': {
      id: '/_app/settings/admin'
      path: '/admin'
      fullPath: '/settings/admin'
      preLoaderRoute: typeof AppSettingsAdminRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/data': {
      id: '/_app/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof AppSettingsDataRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/general': {
      id: '/_app/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/update': {
      id: '/_app/settings/update'
      path: '/update'
      fullPath: '/settings/update'
      preLoaderRoute: typeof AppSettingsUpdateRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/admin/backups': {
      id: '/_app/settings/admin/backups'
      path: '/backups'
      fullPath: '/settings/admin/backups'
      preLoaderRoute: typeof AppSettingsAdminBackupsRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
    '/_app/settings/admin/users': {
      id: '/_app/settings/admin/users'
      path: '/users'
      fullPath: '/settings/admin/users'
      preLoaderRoute: typeof AppSettingsAdminUsersRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
  }
}

interface AppSettingsAdminRouteChildren {
  AppSettingsAdminBackupsRoute: typeof AppSettingsAdminBackupsRoute
  AppSettingsAdminUsersRoute: typeof AppSettingsAdminUsersRoute
}

const AppSettingsAdminRouteChildren: AppSettingsAdminRouteChildren = {
  AppSettingsAdminBackupsRoute: AppSettingsAdminBackupsRoute,
  AppSettingsAdminUsersRoute: AppSettingsAdminUsersRoute,
}

const AppSettingsAdminRouteWithChildren =
  AppSettingsAdminRoute._addFileChildren(AppSettingsAdminRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsAdminRoute: typeof AppSettingsAdminRouteWithChildren
  AppSettingsDataRoute: typeof AppSettingsDataRoute
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
  AppSettingsUpdateRoute: typeof AppSettingsUpdateRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsAdminRoute: AppSettingsAdminRouteWithChildren,
  AppSettingsDataRoute: AppSettingsDataRoute,
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
  AppSettingsUpdateRoute: AppSettingsUpdateRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppArchiveRoute: typeof AppArchiveRoute
  AppDeckRoute: typeof AppDeckRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTrashRoute: typeof AppTrashRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArchiveRoute: AppArchiveRoute,
  AppDeckRoute: AppDeckRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTrashRoute: AppTrashRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
