import { sql } from 'drizzle-orm';
import {
  boolean,
  customType,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';

const tsvector = customType<{ data: string }>({
  dataType: () => 'tsvector',
});

const bytea = customType<{ data: Buffer }>({
  dataType: () => 'bytea',
});

const createdAt = () => timestamp({ withTimezone: true }).notNull().defaultNow();
const updatedAt = () =>
  timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

// Better Auth tables. Field names must match what Better Auth expects.

export const user = pgTable('user', {
  id: text().primaryKey(),
  name: text().notNull(),
  email: text().notNull().unique(),
  emailVerified: boolean().notNull().default(false),
  image: text(),
  role: text().notNull().default('user'),
  lastLoginAt: timestamp({ withTimezone: true }),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export const session = pgTable(
  'session',
  {
    id: text().primaryKey(),
    expiresAt: timestamp({ withTimezone: true }).notNull(),
    token: text().notNull().unique(),
    ipAddress: text(),
    userAgent: text(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [index().on(table.userId)],
);

export const account = pgTable(
  'account',
  {
    id: text().primaryKey(),
    accountId: text().notNull(),
    providerId: text().notNull(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text(),
    refreshToken: text(),
    idToken: text(),
    accessTokenExpiresAt: timestamp({ withTimezone: true }),
    refreshTokenExpiresAt: timestamp({ withTimezone: true }),
    scope: text(),
    password: text(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [index().on(table.userId)],
);

export const verification = pgTable(
  'verification',
  {
    id: text().primaryKey(),
    identifier: text().notNull(),
    value: text().notNull(),
    expiresAt: timestamp({ withTimezone: true }).notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [index().on(table.identifier)],
);

// App tables.

export const notes = pgTable(
  'notes',
  {
    /** UUIDv7 generated by the client so notes can be created offline. */
    id: uuid().primaryKey(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    /** BlockNote document JSON; the source of truth for content. */
    content: jsonb().$type<Record<string, unknown>[]>().notNull().default([]),
    /** Plain text derived from `content` on write. Used for search and export. */
    searchText: text().notNull().default(''),
    search: tsvector().generatedAlwaysAs(sql`to_tsvector('english', search_text)`),
    color: text().notNull().default('default'),
    /** Board column. Null means the note lives in the gallery. */
    status: text(),
    isPinned: boolean().notNull().default(false),
    isArchived: boolean().notNull().default(false),
    /** Fractional index of the note in the user's arrangement (see `positionBetween`). */
    position: text().notNull(),
    /** Normalized URLs of links whose previews the user removed from this note. */
    hiddenLinks: jsonb().$type<string[]>().notNull().default([]),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    /** Set when a note is moved to the trash. DELETE removes it for good. */
    deletedAt: timestamp({ withTimezone: true }),
  },
  (table) => [
    index().on(table.userId, table.updatedAt),
    index('notes_search_idx').using('gin', table.search),
  ],
);

export const boardColumns = pgTable(
  'board_columns',
  {
    id: text().notNull(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    name: text().notNull(),
    color: text().notNull(),
    position: text().notNull(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.id] })],
);

/** File bytes live in ATTACHMENTS_DIR; metadata follows notes through Electric. */
export const attachments = pgTable(
  'attachments',
  {
    id: uuid().primaryKey(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    noteId: uuid()
      .notNull()
      .references(() => notes.id, { onDelete: 'cascade' }),
    name: text().notNull(),
    mimeType: text().notNull(),
    size: integer().notNull(),
    kind: text({ enum: ['image', 'video', 'audio', 'file'] }).notNull(),
    status: text({ enum: ['pending', 'ready'] })
      .notNull()
      .default('pending'),
    sourceId: uuid(),
    createdAt: createdAt(),
    deletedAt: timestamp({ withTimezone: true }),
  },
  (table) => [index().on(table.userId, table.noteId)],
);

/**
 * What the server found at each link in a user's notes, keyed by normalized URL (see
 * `extractLinks`). Rows are added as `pending` when a note gains a link and filled in by the
 * fetch queue (src/linkPreviews), which Electric then streams to the user's devices.
 */
export const linkPreviews = pgTable(
  'link_previews',
  {
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    url: text().notNull(),
    status: text({ enum: ['pending', 'ready', 'failed'] })
      .notNull()
      .default('pending'),
    title: text(),
    description: text(),
    siteName: text(),
    imageHash: text(),
    imageWidth: integer(),
    imageHeight: integer(),
    iconHash: text(),
    /** The site's color as an OKLCH hue, or null when it has no clear one. */
    hue: integer(),
    fetchedAt: timestamp({ withTimezone: true }),
    createdAt: createdAt(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.url] })],
);

/**
 * Thumbnails and site icons, resized on the server and named by the SHA-256 of their bytes.
 * They are copies of public web content, shared by every user who links to them, and are
 * served without auth so plain `<img>` tags can load them (see ADR 0006).
 */
export const linkPreviewAssets = pgTable('link_preview_assets', {
  hash: text().primaryKey(),
  contentType: text().notNull(),
  data: bytea().notNull(),
  createdAt: createdAt(),
});
