import type { Recurrence, ReminderTimes, SharedAttachment } from '@catch/shared';
import { sql } from 'drizzle-orm';
import {
  type AnyPgColumn,
  boolean,
  customType,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

const tsvector = customType<{ data: string }>({
  dataType: () => 'tsvector',
});

const bytea = customType<{ data: Buffer }>({
  dataType: () => 'bytea',
});

const createdAt = () => timestamp({ withTimezone: true }).notNull().defaultNow();
const updatedAt = () =>
  timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

// Better Auth tables. Field names must match what Better Auth expects.

export const user = pgTable('user', {
  id: text().primaryKey(),
  name: text().notNull(),
  email: text().notNull().unique(),
  emailVerified: boolean().notNull().default(false),
  image: text(),
  role: text().notNull().default('user'),
  lastLoginAt: timestamp({ withTimezone: true }),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export const session = pgTable(
  'session',
  {
    id: text().primaryKey(),
    expiresAt: timestamp({ withTimezone: true }).notNull(),
    token: text().notNull().unique(),
    ipAddress: text(),
    userAgent: text(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [index().on(table.userId)],
);

export const account = pgTable(
  'account',
  {
    id: text().primaryKey(),
    accountId: text().notNull(),
    providerId: text().notNull(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text(),
    refreshToken: text(),
    idToken: text(),
    accessTokenExpiresAt: timestamp({ withTimezone: true }),
    refreshTokenExpiresAt: timestamp({ withTimezone: true }),
    scope: text(),
    password: text(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [index().on(table.userId)],
);

export const verification = pgTable(
  'verification',
  {
    id: text().primaryKey(),
    identifier: text().notNull(),
    value: text().notNull(),
    expiresAt: timestamp({ withTimezone: true }).notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [index().on(table.identifier)],
);

/**
 * Sign-up for one account, made by an admin while registration is closed (ADR 0015). Only
 * the hash of the link's token is kept. Server state, not synced to devices.
 */
export const invites = pgTable('invites', {
  id: uuid().primaryKey().defaultRandom(),
  tokenHash: text().notNull().unique(),
  label: text().notNull().default(''),
  createdBy: text()
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  createdAt: createdAt(),
  expiresAt: timestamp({ withTimezone: true }).notNull(),
  usedAt: timestamp({ withTimezone: true }),
  usedBy: text().references(() => user.id, { onDelete: 'set null' }),
});

// App tables.

export const notes = pgTable(
  'notes',
  {
    /** UUIDv7 generated by the client so notes can be created offline. */
    id: uuid().primaryKey(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    /** BlockNote document JSON; the source of truth for content. */
    content: jsonb().$type<Record<string, unknown>[]>().notNull().default([]),
    /** Plain text derived from `content` on write. Used for search and export. */
    searchText: text().notNull().default(''),
    search: tsvector().generatedAlwaysAs(sql`to_tsvector('english', search_text)`),
    color: text().notNull().default('default'),
    /** Board column. Null means the note lives in the gallery. */
    status: text(),
    isPinned: boolean().notNull().default(false),
    isArchived: boolean().notNull().default(false),
    /** Fractional index of the note in the user's arrangement (see `positionBetween`). */
    position: text().notNull(),
    /** Normalized URLs of links whose previews the user removed from this note. */
    hiddenLinks: jsonb().$type<string[]>().notNull().default([]),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    /** Set when a note is moved to the trash. DELETE removes it for good. */
    deletedAt: timestamp({ withTimezone: true }),
  },
  (table) => [
    index().on(table.userId, table.updatedAt),
    index('notes_search_idx').using('gin', table.search),
  ],
);

export const boardColumns = pgTable(
  'board_columns',
  {
    id: text().notNull(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    name: text().notNull(),
    color: text().notNull(),
    position: text().notNull(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.id] })],
);

/** File bytes live in ATTACHMENTS_DIR; metadata follows notes through Electric. */
export const attachments = pgTable(
  'attachments',
  {
    id: uuid().primaryKey(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    noteId: uuid()
      .notNull()
      .references(() => notes.id, { onDelete: 'cascade' }),
    name: text().notNull(),
    mimeType: text().notNull(),
    size: integer().notNull(),
    kind: text({ enum: ['image', 'video', 'audio', 'file'] }).notNull(),
    status: text({ enum: ['pending', 'ready'] })
      .notNull()
      .default('pending'),
    sourceId: uuid(),
    createdAt: createdAt(),
    deletedAt: timestamp({ withTimezone: true }),
  },
  (table) => [index().on(table.userId, table.noteId)],
);

/**
 * What the server found at each link in a user's notes, keyed by normalized URL (see
 * `extractLinks`). Rows are added as `pending` when a note gains a link and filled in by the
 * fetch queue (src/linkPreviews), which Electric then streams to the user's devices.
 */
export const linkPreviews = pgTable(
  'link_previews',
  {
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    url: text().notNull(),
    status: text({ enum: ['pending', 'ready', 'failed'] })
      .notNull()
      .default('pending'),
    title: text(),
    description: text(),
    siteName: text(),
    imageHash: text(),
    imageWidth: integer(),
    imageHeight: integer(),
    iconHash: text(),
    /** The site's color as an OKLCH hue, or null when it has no clear one. */
    hue: integer(),
    fetchedAt: timestamp({ withTimezone: true }),
    createdAt: createdAt(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.url] })],
);

/**
 * Thumbnails and site icons, resized on the server and named by the SHA-256 of their bytes.
 * They are copies of public web content, shared by every user who links to them, and are
 * served without auth so plain `<img>` tags can load them (see ADR 0006).
 */
export const linkPreviewAssets = pgTable('link_preview_assets', {
  hash: text().primaryKey(),
  contentType: text().notNull(),
  data: bytea().notNull(),
  createdAt: createdAt(),
});

/** Tag hierarchy is independent of note content and can be arbitrarily deep. */
export const tags = pgTable(
  'tags',
  {
    id: uuid().primaryKey(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    name: text().notNull(),
    parentId: uuid().references((): AnyPgColumn => tags.id, { onDelete: 'cascade' }),
    icon: text(),
    color: text(),
  },
  (table) => [
    index().on(table.userId, table.parentId),
    uniqueIndex('tags_user_color_idx')
      .on(table.userId, table.color)
      .where(sql`${table.color} IS NOT NULL`),
  ],
);

export const noteTags = pgTable(
  'note_tags',
  {
    id: uuid()
      .primaryKey()
      .references(() => notes.id, { onDelete: 'cascade' }),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    primaryTagId: uuid().references(() => tags.id, { onDelete: 'set null' }),
    secondaryTagIds: jsonb().$type<string[]>().notNull().default([]),
  },
  (table) => [index().on(table.userId)],
);

/**
 * A note's reminder (ADR 0018), at most one, so the note's id is its key. Times are wall
 * clock times; `fireAt` is the instant the scheduler waits for, worked out from them and the
 * zone the user is in, and stays on the server.
 */
export const reminders = pgTable(
  'reminders',
  {
    noteId: uuid()
      .primaryKey()
      .references(() => notes.id, { onDelete: 'cascade' }),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    kind: text({ enum: ['time'] })
      .notNull()
      .default('time'),
    startsAt: text().notNull(),
    timeZone: text().notNull(),
    floating: boolean().notNull().default(true),
    recurrence: jsonb().$type<Recurrence>(),
    nextAt: text(),
    snoozedUntil: timestamp({ withTimezone: true }),
    firedAt: timestamp({ withTimezone: true }),
    fireAt: timestamp({ withTimezone: true }),
    createdAt: createdAt(),
  },
  (table) => [index().on(table.userId), index().on(table.fireAt)],
);

/** Each user's reminder settings: where they were last seen, which is where floating reminders ring. */
export const reminderSettings = pgTable('reminder_settings', {
  userId: text()
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  timeZone: text().notNull(),
  /** The times of day the quick choices use; null until the user changes them. */
  times: jsonb().$type<ReminderTimes>(),
  /** How long Snooze puts a reminder off; null until the user changes it. */
  snoozeMinutes: integer(),
  updatedAt: updatedAt(),
});

/**
 * A note's share link (ADR 0020), at most one, so the note's id is its key. Anyone holding
 * the token reads the note. Removing the row ends the sharing: the link stops working and
 * the note leaves the galleries it was added to.
 */
export const noteShares = pgTable(
  'note_shares',
  {
    noteId: uuid()
      .primaryKey()
      .references(() => notes.id, { onDelete: 'cascade' }),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    token: text().notNull().unique(),
    createdAt: createdAt(),
  },
  (table) => [index().on(table.userId)],
);

/**
 * A shared note in the gallery of someone who added it: a copy of what they may read, which
 * `refreshSharedNote` rewrites in the transaction of every change to the note. A copy, so
 * that this syncs like every other shape, by `user_id` alone. The pin, archive and position
 * are the reader's own.
 */
export const sharedNotes = pgTable(
  'shared_notes',
  {
    /** Whose gallery the note is in. */
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    noteId: uuid()
      .notNull()
      .references(() => noteShares.noteId, { onDelete: 'cascade' }),
    ownerId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    ownerName: text().notNull(),
    content: jsonb().$type<Record<string, unknown>[]>().notNull().default([]),
    color: text().notNull().default('default'),
    attachments: jsonb()
      .$type<(Omit<SharedAttachment, 'createdAt'> & { createdAt: string })[]>()
      .notNull()
      .default([]),
    /** False while the note is in its owner's trash, when the copy is emptied too. */
    isAvailable: boolean().notNull().default(true),
    isPinned: boolean().notNull().default(false),
    isArchived: boolean().notNull().default(false),
    position: text().notNull(),
    /** The note's own dates, not this row's. */
    createdAt: timestamp({ withTimezone: true }).notNull(),
    updatedAt: timestamp({ withTimezone: true }).notNull(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.noteId] }), index().on(table.noteId)],
);

/** A browser that asked for notifications. Server state, not synced to devices. */
export const pushSubscriptions = pgTable(
  'push_subscriptions',
  {
    endpoint: text().notNull(),
    userId: text()
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    p256dh: text().notNull(),
    auth: text().notNull(),
    createdAt: createdAt(),
  },
  // One browser can be signed in to several accounts, and rings for each (ADR 0019).
  (table) => [primaryKey({ columns: [table.endpoint, table.userId] }), index().on(table.userId)],
);

/**
 * The key pair that identifies this server to push services (VAPID). Made on first use and
 * kept here, so a restored backup still reaches the browsers subscribed under it.
 */
export const pushKeys = pgTable('push_keys', {
  id: text().primaryKey(),
  publicKey: text().notNull(),
  privateKey: text().notNull(),
  createdAt: createdAt(),
});
