import type { TagIconName } from '@catch/shared';
import {
  Archive,
  Baby,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  Car,
  ChartNoAxesCombined,
  Check,
  Clock,
  Cloud,
  Code,
  Coffee,
  Dumbbell,
  Film,
  Flag,
  FlaskConical,
  Flower2,
  Folder,
  Footprints,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Heart,
  House,
  Image,
  KeyRound,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  ListTodo,
  Mail,
  MapPin,
  MessageCircle,
  Moon,
  Music,
  Notebook,
  Paintbrush,
  Palette,
  PawPrint,
  Pen,
  Pill,
  Plane,
  Rocket,
  Shield,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Target,
  Train,
  Trees,
  Users,
  Utensils,
  Wallet,
  Wrench,
} from 'lucide-react';

const TAG_ICON_COMPONENTS = {
  tag: Tag,
  briefcase: Briefcase,
  house: House,
  heart: Heart,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  lightbulb: Lightbulb,
  plane: Plane,
  'map-pin': MapPin,
  globe: Globe,
  car: Car,
  bike: Bike,
  train: Train,
  utensils: Utensils,
  coffee: Coffee,
  'shopping-cart': ShoppingCart,
  gift: Gift,
  wallet: Wallet,
  landmark: Landmark,
  'chart-no-axes-combined': ChartNoAxesCombined,
  code: Code,
  laptop: Laptop,
  smartphone: Smartphone,
  camera: Camera,
  image: Image,
  music: Music,
  film: Film,
  'gamepad-2': Gamepad2,
  palette: Palette,
  paintbrush: Paintbrush,
  pen: Pen,
  notebook: Notebook,
  calendar: Calendar,
  clock: Clock,
  check: Check,
  'list-todo': ListTodo,
  target: Target,
  flag: Flag,
  star: Star,
  sparkles: Sparkles,
  rocket: Rocket,
  'flask-conical': FlaskConical,
  wrench: Wrench,
  hammer: Hammer,
  'key-round': KeyRound,
  shield: Shield,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  footprints: Footprints,
  leaf: Leaf,
  'flower-2': Flower2,
  trees: Trees,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  'paw-print': PawPrint,
  baby: Baby,
  users: Users,
  'message-circle': MessageCircle,
  mail: Mail,
  archive: Archive,
  folder: Folder,
  'building-2': Building2,
};

export function TagIcon({ name, className }: { name?: TagIconName | null; className?: string }) {
  const Icon = TAG_ICON_COMPONENTS[name ?? 'tag'];
  return <Icon className={className} aria-hidden />;
}

/** Topics make the picker searchable without exposing icon-library identifiers. */
export const TAG_ICON_LABELS: Record<TagIconName, string> = {
  tag: 'Tag',
  briefcase: 'Work',
  house: 'Home',
  heart: 'Personal',
  'book-open': 'Reading',
  'graduation-cap': 'Education',
  lightbulb: 'Ideas',
  plane: 'Travel',
  'map-pin': 'Places',
  globe: 'World',
  car: 'Car',
  bike: 'Cycling',
  train: 'Transit',
  utensils: 'Food',
  coffee: 'Coffee',
  'shopping-cart': 'Shopping',
  gift: 'Gifts',
  wallet: 'Money',
  landmark: 'Finance',
  'chart-no-axes-combined': 'Growth',
  code: 'Code',
  laptop: 'Technology',
  smartphone: 'Phone',
  camera: 'Photography',
  image: 'Images',
  music: 'Music',
  film: 'Film',
  'gamepad-2': 'Games',
  palette: 'Art',
  paintbrush: 'Design',
  pen: 'Writing',
  notebook: 'Journal',
  calendar: 'Planning',
  clock: 'Time',
  check: 'Done',
  'list-todo': 'Tasks',
  target: 'Goals',
  flag: 'Milestones',
  star: 'Favorites',
  sparkles: 'Inspiration',
  rocket: 'Launch',
  'flask-conical': 'Science',
  wrench: 'Tools',
  hammer: 'DIY',
  'key-round': 'Keys',
  shield: 'Security',
  stethoscope: 'Health',
  pill: 'Medication',
  dumbbell: 'Fitness',
  footprints: 'Walking',
  leaf: 'Nature',
  'flower-2': 'Garden',
  trees: 'Outdoors',
  sun: 'Day',
  moon: 'Night',
  cloud: 'Weather',
  'paw-print': 'Pets',
  baby: 'Family',
  users: 'People',
  'message-circle': 'Conversation',
  mail: 'Email',
  archive: 'Archive',
  folder: 'Files',
  'building-2': 'Business',
};
