#!/usr/bin/env bash
# Creates, initializes and removes Git worktrees, each with its own isolated
# Docker stack. See WORKTREES.md.
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

PORT_BASE=24080
PORT_SPAN=3000
PORT_MAX=28000

slugify() {
    printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's#[^a-z0-9]+#-#g; s#^-+##; s#-+$##'
}

env_value() {
    local file=$1 key=$2
    awk -F= -v key="$key" '$1 == key {sub(/^[^=]*=/, ""); print; exit}' "$file"
}

primary_worktree() {
    git worktree list --porcelain | sed -n 's/^worktree //p' | head -n 1
}

port_is_reserved() {
    local candidate=$1 worktree env_file
    while IFS= read -r worktree; do
        env_file="$worktree/.env.worktree"
        [[ -f "$env_file" ]] || continue
        [[ "$(env_value "$env_file" CATCH_PORT)" == "$candidate" ]] && return 0
    done < <(git worktree list --porcelain | sed -n 's/^worktree //p')

    if command -v ss >/dev/null 2>&1; then
        ss -H -ltn "sport = :$candidate" 2>/dev/null | grep -q . && return 0
    fi
    return 1
}

choose_port() {
    local seed candidate
    seed=$(printf '%s' "$repo_root" | cksum | awk '{print $1}')
    candidate=$((PORT_BASE + seed % PORT_SPAN))
    while port_is_reserved "$candidate"; do
        candidate=$((candidate + 1))
        if ((candidate > PORT_MAX)); then
            echo "Could not allocate a free development port." >&2
            exit 1
        fi
    done
    printf '%s' "$candidate"
}

# The Tailscale MagicDNS short name when available, so stacks are reachable
# from other devices on the tailnet; localhost otherwise.
detect_public_host() {
    local dns_name
    if command -v tailscale >/dev/null 2>&1; then
        dns_name=$(tailscale status --self --json 2>/dev/null \
            | sed -n 's/.*"DNSName": *"\([^".]*\)\..*/\1/p' | head -n 1 || true)
        [[ -n "$dns_name" ]] && { printf '%s' "$dns_name"; return; }
    fi
    printf 'localhost'
}

random_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -base64 32
    else
        head -c 32 /dev/urandom | base64
    fi
}

init_worktree() {
    local branch slug path_hash project env_file common_dir port public_host
    env_file="$repo_root/.env.worktree"
    if [[ -e "$env_file" ]]; then
        echo "$env_file already exists; leaving it unchanged."
        "$repo_root/scripts/dev.sh" url
        return
    fi

    common_dir=$(git rev-parse --path-format=absolute --git-common-dir)
    exec 9>"$common_dir/catch-worktree-allocation.lock"
    command -v flock >/dev/null 2>&1 && flock 9

    branch=$(git branch --show-current)
    slug=$(slugify "${branch:-detached}")
    # Cutting the slug can leave a dash at its end, and Docker refuses `-_` in an image name.
    slug=${slug:0:28}
    path_hash=$(printf '%s' "$repo_root" | cksum | awk '{print $1}')
    project="catch_${slug%-}_${path_hash:0:7}"
    port=$(choose_port)
    public_host=${CATCH_PUBLIC_HOST:-$(detect_public_host)}

    umask 077
    cat > "$env_file" <<ENV
# Generated by scripts/worktree.sh for this checkout only. Not committed.
COMPOSE_PROJECT_NAME=$project
COMPOSE_REMOVE_ORPHANS=1
CATCH_PORT=$port
CATCH_PUBLIC_HOST=$public_host
CATCH_DEV_BIND_ADDRESS=0.0.0.0
CATCH_SEED_PROFILE=demo
BETTER_AUTH_SECRET=$(random_secret)
ENV

    echo "Initialized isolated development environment:"
    echo "  Project: $project"
    echo "  URL:     http://$public_host:$port"
    echo "  Config:  $env_file"
    echo
    echo "Start it with: ./scripts/dev.sh up"
}

create_worktree() {
    local branch=$1 target name
    git check-ref-format --branch "$branch" >/dev/null
    # A primary checkout named like `catch-main` yields siblings like `catch-<branch>`.
    name="$(basename "$repo_root")"
    name="${name%-main}-$(slugify "$branch")"
    target=${2:-"$(dirname "$repo_root")/$name"}

    if [[ -n "$(git status --porcelain)" ]]; then
        echo "Note: uncommitted changes in $repo_root are not copied into the new worktree."
    fi
    if git show-ref --verify --quiet "refs/heads/$branch"; then
        git worktree add "$target" "$branch"
    else
        git worktree add -b "$branch" "$target" HEAD
    fi
    target=$(cd "$target" && pwd)
    (cd "$target" && ./scripts/worktree.sh init)
    echo "Worktree ready at $target"
}

resolve_worktree() {
    local query=$1
    [[ ! -d "$query" ]] || query=$(cd "$query" && pwd -P)
    git worktree list --porcelain | awk -v query="$query" '
        /^worktree / { path = substr($0, 10); branch = "" }
        /^branch / { branch = substr($0, 8); sub(/^refs\/heads\//, "", branch) }
        /^$/ {
            if (path == query || branch == query) { print path "\t" branch; found = 1; exit }
        }
        END {
            if (!found && (path == query || branch == query)) print path "\t" branch
        }
    ' | head -n 1
}

# Ignored paths that are safe to discard when removing a worktree: dependencies,
# build output, test artifacts and Android build products.
DISPOSABLE='(^|/)(node_modules|dist|dev-dist|coverage|playwright-report|test-results|\.tanstack|\.gradle|build|capacitor-cordova-android-plugins)(/|$)|(^|/)(local\.properties|capacitor\.config\.json)$|apps/web/android/app/src/main/assets/|(^|/)res/xml/config\.xml$|\.(tsbuildinfo|log|apk)$'

remove_worktree() {
    local query=$1
    shift
    local delete_branch=false bypass=false allow_artifacts=true option
    local match target branch status ignored filter
    for option in "$@"; do
        case "$option" in
            --delete-branch) delete_branch=true ;;
            -y|--yes) bypass=true ;;
            --strict) allow_artifacts=false ;;
            *) echo "Unknown remove option: $option" >&2; exit 2 ;;
        esac
    done
    match=$(resolve_worktree "$query")
    [[ -n "$match" ]] || { echo "No worktree found for '$query'." >&2; exit 1; }
    IFS=$'\t' read -r target branch <<< "$match"
    [[ "$target" != "$(primary_worktree)" ]] || { echo "Refusing to remove the primary worktree." >&2; exit 1; }
    [[ "$target" != "$repo_root" ]] || { echo "Run removal from another worktree, or use self-remove." >&2; exit 1; }

    status=$(git -C "$target" status --porcelain --untracked-files=all)
    [[ -z "$status" ]] || { echo "Refusing to remove a dirty worktree:" >&2; printf '%s\n' "$status" >&2; exit 1; }

    filter='^\.env\.worktree$'
    $allow_artifacts && filter="$filter|$DISPOSABLE"
    ignored=$(
        git -C "$target" -c core.quotePath=false status --porcelain --ignored --untracked-files=all -z \
            | tr '\0' '\n' \
            | sed -n 's/^!! //p' \
            | grep -E -v "$filter" || true
    )
    if [[ -n "$ignored" ]]; then
        echo "Refusing to remove a worktree containing unexpected ignored files:" >&2
        printf '%s\n' "$ignored" >&2
        echo "Move or remove those files explicitly, then retry." >&2
        exit 1
    fi

    if [[ -f "$target/.env.worktree" && -x "$target/scripts/dev.sh" ]]; then
        if [[ -n "$(find "$target" -path "$target/.git" -prune -o -type d ! -writable -print -quit)" ]]; then
            "$target/scripts/dev.sh" fix-permissions
        fi
        if $bypass; then
            "$target/scripts/dev.sh" destroy -y
        else
            "$target/scripts/dev.sh" destroy
        fi
        rm -f "$target/.env.worktree"
    fi
    git worktree remove --force "$target"
    echo "Removed worktree: $target"
    if $delete_branch && [[ -n "$branch" ]]; then
        git branch -d "$branch"
    elif [[ -n "$branch" ]]; then
        echo "Branch preserved: $branch"
    fi
}

self_remove_worktree() {
    local primary
    primary=$(primary_worktree)
    [[ "$repo_root" != "$primary" ]] || { echo "Refusing to self-remove the primary worktree." >&2; exit 1; }
    [[ -x "$primary/scripts/worktree.sh" ]] || { echo "The primary worktree has no executable cleanup script." >&2; exit 1; }
    cd "$primary"
    exec "$primary/scripts/worktree.sh" remove "$repo_root" "$@"
}

remove_all_worktrees() {
    local option target
    local -a targets=()
    [[ "$repo_root" == "$(primary_worktree)" && "$(git branch --show-current)" == main ]] || {
        echo "Run remove-all from the primary worktree on main." >&2
        exit 1
    }
    for option in "$@"; do
        case "$option" in
            --delete-branch|-y|--yes|--strict) ;;
            *) echo "Unknown remove-all option: $option" >&2; exit 2 ;;
        esac
    done

    mapfile -t targets < <(git worktree list --porcelain | sed -n 's/^worktree //p')
    for target in "${targets[@]}"; do
        [[ "$target" == "$repo_root" ]] && continue
        remove_worktree "$target" "$@"
    done
}

list_worktrees() {
    local worktree env_file
    while IFS= read -r worktree; do
        env_file="$worktree/.env.worktree"
        if [[ -f "$env_file" ]]; then
            printf '%s\thttp://%s:%s\n' "$worktree" \
                "$(env_value "$env_file" CATCH_PUBLIC_HOST)" "$(env_value "$env_file" CATCH_PORT)"
        else
            printf '%s\t(not initialized)\n' "$worktree"
        fi
    done < <(git worktree list --porcelain | sed -n 's/^worktree //p')
}

usage() {
    cat <<'USAGE'
Usage:
  ./scripts/worktree.sh init
  ./scripts/worktree.sh create <branch> [target-directory]
  ./scripts/worktree.sh list
  ./scripts/worktree.sh remove <branch-or-path> [--delete-branch] [-y|--yes] [--strict]
  ./scripts/worktree.sh remove-all [--delete-branch] [-y|--yes] [--strict]
  ./scripts/worktree.sh self-remove [--delete-branch] [-y|--yes] [--strict]
USAGE
}

case "${1:-}" in
    init) init_worktree ;;
    create) [[ $# -ge 2 ]] || { usage >&2; exit 1; }; create_worktree "$2" "${3:-}" ;;
    list) list_worktrees ;;
    remove) [[ $# -ge 2 ]] || { usage >&2; exit 1; }; shift; remove_worktree "$@" ;;
    remove-all) shift; remove_all_worktrees "$@" ;;
    self-remove) shift; self_remove_worktree "$@" ;;
    *) usage >&2; exit 1 ;;
esac
